version: '3.3'
services:
  db:
    image: postgres:9.6.9-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  default:
volumes:
  pg_data:
