version: '3.3'
services:
  db:
    image: rabbitmq:3.8.16-management-alpine
    networks:
      - default
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data/db

networks:
  default:
volumes:
  rabbitmq_data:
