version: '3.3'
services:
  selenium-hub:
    container_name: selenium_hub
    image: selenium/hub:3.12.0-cobalt
    ports:
      - 4444:4444
    networks:
      - default

  selenium-chrome:
    container_name: selenium_chrome
    image: selenium/node-chrome:3.12.0-cobalt
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
    networks:
      - default
    depends_on:
      - selenium-hub

  selenium-firefox:
    container_name: selenium_firefox
    image: selenium/node-firefox:3.12.0-cobalt
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
    networks:
      - default
    depends_on:
      - selenium-hub

networks:
  default:
