version: '3.3'
services:
  db:
    image: dpage/pgadmin4:3.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    networks:
      - default
    ports:
      - 5431:80
    volumes:
      - pga_data:/var/lib/pgadmin

networks:
  default:
volumes:
  pga_data:
