#!/bin/bash

docker run -e POSTGRES_USER=postgres \
           -e POSTGRES_PASSWORD=postgres \
           -e POSTGRES_DB=postgres \
           -e PGDATA=/var/lib/postgresql/data/pgdata \
           -v 115_pg_data:/var/lib/postgresql/data \
           -p 5432:5432 \
           -d \
           postgres:11.5-alpine
