version: '3.3'
services:
  elasticsearch_master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch_master
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    ports:
      - 9200:9200
    volumes:
      - es_cluster_master_data:/usr/share/elasticsearch/data

  elasticsearch_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch_node
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_cluster_node_data:/usr/share/elasticsearch/data
    networks:
      - default

networks:
  default:
volumes:
  es_cluster_master_data:
  es_cluster_node_data:
