version: '3.3'
services:
  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - pg10-data:/var/lib/postgresql/data

networks:
  default:
volumes:
  pg10-data:
